
<section class="home-static-block">
	<?php
    //	echo $this->getLayout()->createBlock("Magento\Cms\Block\Block")->setBlockId("home-block")->toHtml();
    echo $this->getLayout()->createBlock("Magento\Cms\Block\Block")->setBlockId("custom-home")->toHtml();
	?>
</section>

<section class="best-selling-product home-product-slider">
	<?php
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$productBlock = $objectManager->get('\Magento\Catalog\Block\Product\AbstractProduct');
        $productCollection = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Product\Collection');
		$reportCollection = $objectManager->create('Magento\Reports\Model\ResourceModel\Report\Collection\Factory');
		$items = $reportCollection->create('Magento\Sales\Model\ResourceModel\Report\Bestsellers\Collection');
		$items->setPeriod('month');
		//$items->setPeriod('year');
		//$items->setPeriod('day');
        $productIds = [];
		foreach ($items as $item) {
            array_push($productIds, $item->getProductId());
		}
        if($productIds){
            $image = 'new_products_content_widget_grid';
            $productIds = array_unique($productIds);
        }else{
            $productIds = [0];
        }
        $productCollection = $productCollection->addAttributeToSelect('*')->addAttributeToFilter('entity_id',$productIds);
//        $productCollection = $this->helper('Zou\Demo\Helper\Data')->getBestSellerProducts();
	?>
	<div class="block-products-list grid">
        <div class="block-title">
            <h1><?php /* @escapeNotVerified */ echo __('Hot Sellers'); ?></h1>
        </div>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-owl-carousel owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($productCollection as $_item): ?>
                    <?php
                        if(!$_item->isSaleable()){
                            continue;
                        }
                    ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item-owl">' : '</li><li class="product-item-owl">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $productBlock->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $productBlock->getImage($_item, $image)->toHtml(); ?>
                            </a>

                            <div class="product-item-details">
                            <a class="product-item-details-link" href="<?php /* @escapeNotVerified */ echo $productBlock->getProductUrl($_item) ?>">
                                <div class="product_title_box">

                                <div class="product_name_price_details">
                                    <strong class="product-item-name">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </strong>

                                    <?php
                                    echo $productBlock->getProductPrice($_item);
                                    ?>
                                </div>
                                </div>
                               </a>
                            </div>
						</div>
						<?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    	<?php endforeach ?>
					</ol>
				</div>
		</div>
	</div>
</section>


<section class="category-product-list home-product-slider">
    <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $productBlock = $objectManager->get('\Magento\Catalog\Block\Product\AbstractProduct');
        $catalogConfig = $objectManager->get('\Magento\Catalog\Model\Config');
        $productCollection = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Product\Collection');
        $categoryModel = $objectManager->get('\Magento\Catalog\Model\Category');
        $scopeConfig = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
        //$categoryId = $scopeConfig->getValue('demo/special_categories/home_product_slider_category',\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
        //var_dump($categoryId);
        $categoryId = 49;
        $category = $categoryModel->load($categoryId);

        $productCollection = $productCollection
            ->setVisibility([2,3,4])
            ->addAttributeToFilter('status', ['in' => [1]])
            ->addMinimalPrice()
            ->addFinalPrice()
            ->addTaxPercents()
            ->addAttributeToSelect($catalogConfig->getProductAttributes())
            ->addUrlRewrite()
            ->addStoreFilter()
            ->setPageSize(8)
            ->setCurPage(1)
            ->addCategoryFilter($category);
        $image = 'new_products_content_widget_grid';
    ?>
    <div class="block-products-list grid">
        <div class="block-title">
            <h1><?php /* @escapeNotVerified */ echo $category->getName(); ?></h1>
        </div>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-owl-carousel owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($productCollection as $_item): ?>
                    <?php
                        if(!$_item->isSaleable()){
                            continue;
                        }
                    ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item-owl">' : '</li><li class="product-item-owl">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $productBlock->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $productBlock->getImage($_item, $image)->toHtml(); ?>
                            </a>

                            <div class="product-item-details">
                            <a class="product-item-details-link" href="<?php /* @escapeNotVerified */ echo $productBlock->getProductUrl($_item) ?>">
                                <div class="product_title_box">

                                <div class="product_name_price_details">
                                    <strong class="product-item-name">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </strong>

                                    <?php
                                    echo $productBlock->getProductPrice($_item);
                                    ?>
                                </div>
                                </div>
                               </a>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
        </div>
    </div>
</section>
