<div class="footer_info_box">
	<div class="super-inner footer_info_list col-xs-12 footer-top">
		<h4>Legal information</h4>
		<ul>
			<li><a>Terms and Conditions</a></li>
			<li><a>Privacy Policy</a></li>
			<li><a>Right of Withdrawal</a></li>
			<li><a>Imprint/Contact</a></li>
		</ul>
	</div>
	<div class="super-inner footer_info_list col-xs-12 footer-center">
		<div id="NavElement_21110" class=" NavBarElement0">
			<div class="NavigationText ">
				<h4>Follow us</h4>
			</div>
		</div>
		<div class="footer-social-media-icons">
			<span class="whitebox">
				<a class="social facebook" title="Facebook" target="_blank" href="https://facebook.com/"> <span class="fa fa-facebook-square"></span> </a>
			</span>
			<span class="whitebox">
				<a class="social instagram" title="Instagram" target="_blank" href="https://acebook.com/"> <span class="fa fa-instagram"></span> </a>
			</span>
			<span class="whitebox">
				<a class="social twitter" title="Twitter" target="_blank" href="https://twitter.com/"> <span class="fa fa-twitter-square"></span> </a>
			</span>
		</div>
	</div>
	<div class="super-inner footer_info_list col-xs-12 footer-bottom">
		<h4>Customer information</h4>
		<ul>
			<li><a>Payment and Prices</a></li>
			<li><a>Shipping and Returns</a></li>
			<li><a href="http://bbs.mallol.cn/" target="_blank">About Us</a></li>
			<li><a>My Account</a></li>
		</ul>
	</div>
	<div class="copyright footer_info_list col-xs-12">
	 	<span>
	 		<div id="NavElement_21110" class=" NavBarElement0">
				<div class="NavigationText ">©&nbsp;<a href="http://bbs.mallol.cn/" target="_blank">Magento2Demo</a>&nbsp;<span>2018</span>. All rights reserved.</div>
			</div>
			<div class="NavigationText"></div>
			<div id="NavElement_166530" class=" NavBarElement2"></div>
			<div><span style="color: #999999; font-family: Arial, Verdana, Helvetica; font-size: 0px; text-align: center; white-space: nowrap; background-color: #454545;"><br></span>
			</div>
		</span>
	</div>
</div>