<div class="row">
    <div class="col-xs-12 col-ms-12 col-md-12">
        <h1 class="physicalstore-box-title"><?php echo __('Physical Stores') ?></h1>
        <p class="letter_small_title"><?php echo __('Physical Stores Infomation') ?></p>   
        <div class="physicalstore-store-right">
            <div class="row">
                <!--store loop start-->
                <?php
                $storeList = $this->getPhysicalStores();
                $countryList = $this->getCountry();
                foreach ($storeList as $_store):?>
                    <?php
                    $name = $_store->getName();
                    $urlKey = $_store->getUrlKey();
                    $phone = $_store->getPhone();
                    $openingHours = $_store->getOpeningHours();
                    $openingHours = unserialize($openingHours);
                    $street = $_store->getStreet();
                    $postcode = $_store->getPostcode();
                    $city = $_store->getCity();
                    $latitude = $_store->getLatitude();
                    $longitude = $_store->getLongitude();
                    //$url = $this->getUrl('physicalstore/' . $urlKey);
                    $url = $this->getUrl('demo/physicalstore/view',array('url_key' =>$urlKey));
                    $countryCode = $_store->getCountryCode();
                    foreach ($countryList as $v) {
                        if ($v['value'] == $countryCode) {
                            $googleMapsAddr = $street . "," . $postcode . "," . $city . "," . $v['label'];
                        }
                    }
                    if (!empty($latitude) && !empty($longitude)) {
                        $location = $latitude . "," . $longitude;
                    } else {
                        $location = $googleMapsAddr;
                    }
                    $googleStaticMapUrl = '';
                    //$googleStaticMapUrl = "http://maps.googleapis.com/maps/api/staticmap?zoom=10&size=270x200&markers=color:red|{$location}&sensor=false&key=AIzaSyAd33exzXEitJ1XEDUVyWrr48g3RP4Gpw0";
                    ?>

                    <div class="col-xs-12 col-ms-6 col-md-6 physicalstore-box-list">
                        <div class="physicalstore-box">
                            <div class="row">
                                <!-- <script type="text/javascript"
                                        src="https://apis.google.com/js/plusone.js" gapi_processed="true">
                                        {
                                            lang: 'zh'
                                        }
                                </script> -->
                                <div class=" colo-xs-12 col-ms-6 col-md-7 physicalstore_l_bar_box">		      
                                    <h1  class="physicalstore-box-titles"><?php echo $name; ?></h1>
                                    <div class="small-map" width="270" height="200">
                                        <a target="_blank" href="http://maps.google.com?q=<?php echo $googleMapsAddr; ?>">
                                            <img class="border-top"  width="270" height="200" src="<?php echo $googleStaticMapUrl; ?>" alt="" />
                                        </a>
                                    </div>
                                    <a href="<?php echo 'http://maps.google.com?q=' . $googleMapsAddr; ?>"><span class="physicalstore-box-titlesml"><?php echo __('Look at the magnified map') ?></span></a>
                                </div>		   	   
                                <div class=" colo-xs-12  col-ms-6 col-md-5 physicalstore_r_bar_box">
                                    <p><strong><?php echo $street . ',&nbsp' . $postcode . '&nbsp' . $name; ?></strong><br>
                                        <?php echo __('Opening hours:') ?><br>
                                        <?php foreach ((array) $openingHours as $_hour): ?>
                                            <?php echo $_hour['day'] . ': ' . $_hour['time'] ?>
                                            <br>
                                        <?php endforeach; ?><br>
                                        <?php echo __('Phone. ') . $phone; ?>
                                        <br> 
                                        <?php if ($this->isEnabledStaffs()): ?>
                                            <a class="physicalstore-view-btn" href="<?php echo $url; ?>"><?php echo __('more information') ?>   »</a></p>	
                                        <?php endif;?>
                                </div>   
                            </div>
                        </div>
                    </div>  
                <?php endforeach; ?>
            </div>  
        </div>
    </div>
</div>
